Repository forfun-flowing/frontend, pull requests merged in 2024-03, with the labels that each got.

#61 소셜 로그인 로직 구현 & API 모듈화
  .gitignore
  package.json
  public/svg/google.svg
  public/svg/join-step1.svg
  public/svg/kakao.svg
  src/apis/auth/apis.ts
  src/apis/auth/index.ts
  src/apis/auth/keys.ts
  src/apis/auth/queries.ts
  src/apis/auth/type.ts
  src/apis/config/common.ts
  src/apis/config/error.ts
  src/apis/config/instance.ts
  src/app/(mood)/join/components/FunnelContext.tsx
  src/app/(mood)/join/components/StepTitle.tsx
  src/app/(mood)/join/funnels/step1/Step1.tsx
  src/app/(mood)/join/funnels/step2/Step2.tsx
  src/app/(mood)/join/funnels/step2/components/BirthdaySection.tsx
  src/app/(mood)/join/funnels/step2/components/BodyTypeBottomSheet.tsx
  src/app/(mood)/join/funnels/step2/components/BodyTypeDropBox.tsx
  src/app/(mood)/join/funnels/step2/components/BodyTypeSection.tsx
  src/app/(mood)/join/funnels/step2/components/Keywords.tsx
  src/app/(mood)/join/funnels/step2/components/MbtiBottomSheet.tsx
  src/app/(mood)/join/funnels/step2/components/MbtiSection.tsx
  src/app/(mood)/join/funnels/step2/components/MoodBoard.tsx
  src/app/(mood)/join/funnels/step2/components/MoodForm.tsx
  src/app/(mood)/join/funnels/step2/components/MyKeywordPopup.tsx
  src/app/(mood)/join/funnels/step2/components/MyKeywordSection.tsx
  src/app/(mood)/join/funnels/step2/components/PostCodePopup.tsx
  src/app/(mood)/join/funnels/step2/components/RegionSection.tsx
  src/app/(mood)/join/funnels/step2/components/SectionLabel.tsx
  src/app/(mood)/join/funnels/step2/components/ToggleButton.tsx
  src/app/(mood)/join/funnels/step2/components/WaitingHeader.tsx
  src/app/(mood)/join/funnels/step3/Step3.tsx
  src/app/(mood)/join/page.tsx
  src/app/(sub)/auth/google/page.tsx
  src/app/(sub)/auth/kakao/page.tsx
  src/app/(sub)/login/page.tsx
  src/app/page.tsx
  src/constants/environment.ts
  src/constants/index.ts
  src/constants/token.ts
  src/types/index.d.ts
  src/utils/index.ts
  src/utils/token.ts
  yarn.lock
Labels: 기능구현 ✅

#63 헤더 연관 컴포넌트 리펙토링
  src/app/(main)/chatting/page.tsx
  src/app/(main)/feed/detail/[id]/page.tsx
  src/app/(main)/feed/page.tsx
  src/app/(main)/mypage/page.tsx
  src/components/Header/FeedHeader.tsx
  src/components/Header/Header.tsx
  src/components/Header/JoinHeader.tsx
  src/components/Header/MenuButton.tsx
  src/components/Header/TextHeader.tsx
  src/components/Header/index.ts
  src/components/Motion.tsx
Labels: 리펙토링 ♻️

#64 나의 가치관 페이지 - Step4 구현
  public/svg/heart-button-off.svg
  public/svg/heart-button-on.svg
  public/svg/job-bw.svg
  public/svg/job-color.svg
  public/svg/life-bw.svg
  public/svg/life-color.svg
  public/svg/love-bw.svg
  public/svg/love-color.svg
  src/apis/auth/keys.ts
  src/apis/auth/queries.ts
  src/apis/config/instance.ts
  src/apis/question/apis.ts
  src/apis/question/index.ts
  src/apis/question/keys.ts
  src/apis/question/queries.ts
  src/apis/question/type.ts
  src/app/(mood)/join/components/WaitingHeader.tsx
  src/app/(mood)/join/funnels/JoinFunnel.tsx
  src/app/(mood)/join/funnels/step2/components/BodyTypeBottomSheet.tsx
  src/app/(mood)/join/funnels/step4/Step4.tsx
  src/app/(mood)/join/funnels/step4/components/QuestionList.tsx
  src/app/(mood)/join/funnels/step4/components/Step4Context.tsx
  src/app/(mood)/join/funnels/step4/components/TabBar.tsx
  src/app/(mood)/join/funnels/step5/Step5.tsx
  src/app/(mood)/join/page.tsx
  src/assets/MyValue.tsx
  src/components/Radio.tsx
  src/providers/HydrationProvider.tsx
Labels: 기능구현 ✅

#67 Axios interceptors request 로직으로 인해 API 요청이 가지 않는 문제를 해결한다
  src/apis/config/instance.ts
Labels: 버그 🚨

#72 스토리북 세팅 및 import 순서 정렬 라이브러리 설치
  .eslintrc.js
  .github/issue_template.md
  .github/pull_request_template.md
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  yarn.lock
Labels: 설정 ⚙️

#74 import 순서 정렬
  src/apis/auth/queries.ts
  src/apis/config/instance.ts
  src/apis/question/queries.ts
  src/app/(main)/home/components/HomeHeader.tsx
  src/app/(mood)/join/components/AnimatePresenceLayout.tsx
  src/app/(mood)/join/components/BackButton.tsx
  src/app/(mood)/join/components/FunnelContext.tsx
  src/app/(mood)/join/components/PopupHeader.tsx
  src/app/(mood)/join/components/WaitingHeader.tsx
  src/app/(mood)/join/funnels/JoinFunnel.tsx
  src/app/(mood)/join/funnels/step1/Step1.tsx
  src/app/(mood)/join/funnels/step2/Step2.tsx
  src/app/(mood)/join/funnels/step2/components/BirthdaySection.tsx
  src/app/(mood)/join/funnels/step2/components/BodyTypeBottomSheet.tsx
  src/app/(mood)/join/funnels/step2/components/BodyTypeDropBox.tsx
  src/app/(mood)/join/funnels/step2/components/BodyTypeSection.tsx
  src/app/(mood)/join/funnels/step2/components/Keywords.tsx
  src/app/(mood)/join/funnels/step2/components/MbtiBottomSheet.tsx
  src/app/(mood)/join/funnels/step2/components/MbtiSection.tsx
  src/app/(mood)/join/funnels/step2/components/MoodBoard.tsx
  src/app/(mood)/join/funnels/step2/components/MoodForm.tsx
  src/app/(mood)/join/funnels/step2/components/MyKeywordPopup.tsx
  src/app/(mood)/join/funnels/step2/components/MyKeywordSection.tsx
  src/app/(mood)/join/funnels/step2/components/PostCodePopup.tsx
  src/app/(mood)/join/funnels/step2/components/RegionSection.tsx
  src/app/(mood)/join/funnels/step2/components/ToggleButton.tsx
  src/app/(mood)/join/funnels/step3/Step3.tsx
  src/app/(mood)/join/funnels/step4/Step4.tsx
  src/app/(mood)/join/funnels/step4/components/QuestionList.tsx
  src/app/(mood)/join/funnels/step4/components/Step4Context.tsx
  src/app/(mood)/join/funnels/step4/components/TabBar.tsx
  src/app/(mood)/join/funnels/step5/Step5.tsx
  src/app/(mood)/join/page.tsx
  src/app/(sub)/auth/google/page.tsx
  src/app/(sub)/auth/kakao/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/LeftArrow.tsx
  src/components/Button/ButtonWrapper.tsx
  src/components/Header/BackButton.tsx
  src/components/Header/Header.tsx
  src/components/Input.tsx
  src/components/Modal/AnimatePortal.tsx
  src/components/Modal/BottomSheet.tsx
  src/components/Modal/PopupContainer.tsx
  src/components/Radio.tsx
  src/components/Spacing.tsx
  src/components/Tabs/BottomTabs.tsx
  src/hooks/useBottomSheet.ts
  src/hooks/useOverlay.tsx
  src/providers/HydrationProvider.tsx
  src/providers/OverlayProvider.tsx
  src/providers/Providers.tsx
  src/utils/cn.ts
  src/utils/token.ts
Labels: 클린업 🧹

#79 prettier-plugin-tailwindcss가 적용되지 않는 문제를 해결한다.
  .prettierrc
  package.json
  yarn.lock
Labels: 버그 🚨

#81 로그인 후 적절한 가입 페이지로 매핑한다
  package.json
  src/apis/config/instance.ts
  src/apis/member/apis.ts
  src/apis/member/index.ts
  src/apis/member/keys.ts
  src/apis/member/queries.ts
  src/apis/member/type.ts
  src/apis/profile/apis.ts
  src/apis/profile/index.ts
  src/apis/profile/mutations.ts
  src/apis/profile/type.ts
  src/app/(mood)/join/components/Join1Context.tsx
  src/app/(mood)/join/funnels/JoinFunnel.tsx
  src/app/(mood)/join/funnels/step1/Step1.tsx
  src/app/(mood)/join/funnels/step2/components/BirthdaySection.tsx
  src/app/(mood)/join/funnels/step2/components/BodyTypeSection.tsx
  src/app/(mood)/join/funnels/step2/components/MbtiSection.tsx
  src/app/(mood)/join/funnels/step2/components/MoodForm.tsx
  src/app/(mood)/join/funnels/step2/components/MyKeywordSection.tsx
  src/app/(mood)/join/funnels/step2/components/PostCodePopup.tsx
  src/app/(mood)/join/funnels/step4/Step4.tsx
  src/app/(mood)/join/funnels/step4/components/QuestionList.tsx
  src/app/(sub)/auth/google/page.tsx
  src/app/(sub)/auth/kakao/page.tsx
  src/app/globals.css
  src/types/index.d.ts
  src/utils/token.ts
  yarn.lock
Labels: 기능구현 ✅

#84 Step5 API 연동 & Step6 페이지 구현
  next.config.js
  package.json
  src/apis/file/api.ts
  src/apis/file/mutations.ts
  src/apis/file/type.ts
  src/apis/profile/apis.ts
  src/apis/profile/mutations.ts
  src/app/(mood)/join/funnels/JoinFunnel.tsx
  src/app/(mood)/join/funnels/step1/Step1.tsx
  src/app/(mood)/join/funnels/step2/components/PostCodePopup.tsx
  src/app/(mood)/join/funnels/step5/Step5.tsx
  src/app/(mood)/join/funnels/step6/Step6.tsx
  src/utils/age.ts
  src/utils/compressImage.ts
  src/utils/fileReader.ts
  src/utils/index.ts
  yarn.lock
Labels: 기능구현 ✅

#85 토스트 컴포넌트 & 훅 구현
  public/svg/warning.svg
  src/app/(mood)/join/funnels/step2/components/BodyTypeBottomSheet.tsx
  src/app/(mood)/join/funnels/step2/components/MbtiBottomSheet.tsx
  src/app/(mood)/join/funnels/step2/components/MyKeywordPopup.tsx
  src/app/(mood)/join/funnels/step2/components/PostCodePopup.tsx
  src/app/(mood)/join/funnels/step4/Step4.tsx
  src/app/(mood)/join/funnels/step4/components/QuestionList.tsx
  src/app/(mood)/join/funnels/step5/Step5.tsx
  src/components/Overlay/AnimatePortal.tsx
  src/components/Overlay/BottomDim.tsx
  src/components/Overlay/BottomSheet.tsx
  src/components/Overlay/PopupContainer.tsx
  src/components/Overlay/Portal.tsx
  src/components/Overlay/Toast.tsx
  src/components/Overlay/index.ts
  src/hooks/useOverlay.tsx
  src/hooks/useToast.tsx
Labels: 기능구현 ✅

#89 로그인 페이지 서비스 소개 캐러셀 구현
  public/svg/service-intro-1.svg
  public/svg/service-intro-2.svg
  public/svg/service-intro-3.svg
  src/app/(sub)/join/funnels/step6/Step6.tsx
  src/app/page.tsx
  src/components/Overlay/BottomSheet.tsx
  src/constants/motions.ts
Labels: 기능구현 ✅

#92 온보딩 페이지 반응형 대응 이슈 수정
  public/image/onboarding1.png
  public/image/onboarding2.png
  public/image/onboarding3.png
  public/svg/service-intro-1.svg
  public/svg/service-intro-2.svg
  public/svg/service-intro-3.svg
  src/app/globals.css
  src/app/page.tsx
Labels: 버그 🚨

#93 피드에 들어가는 컴포넌트 구현 및 목록 조회
  public/svg/comment.svg
  src/apis/feed/apis.ts
  src/apis/feed/index.ts
  src/apis/feed/keys.ts
  src/apis/feed/queries.ts
  src/apis/feed/type.ts
  src/app/(main)/feed/components/ChannelBadge.tsx
  src/app/(main)/feed/components/CommentCount.tsx
  src/app/(main)/feed/components/FeedItem.tsx
  src/app/(main)/feed/components/LikeCount.tsx
  src/app/(main)/feed/page.tsx
  src/components/Avatar.tsx
Labels: 기능구현 ✅
