Repository forfun-flowing/frontend, pull requests merged in 2024-04, with the labels that each got.

#98 내 프로필 페이지를 구현하고 미들웨어 라우팅 가드 로직을 보완한다.
  src/apis/config/fetch.ts
  src/app/(sub)/join/components/WaitingHeader.tsx
  src/app/(sub)/join/funnels/JoinFunnel.tsx
  src/app/(sub)/join/funnels/step1/Step1.tsx
  src/app/(sub)/join/funnels/step2/components/MyKeywordPopup.tsx
  src/app/(sub)/join/funnels/step4/components/QuestionList.tsx
  src/app/(sub)/join/funnels/step5/Step5.tsx
  src/app/(sub)/join/funnels/step6/Step6.tsx
  src/app/(sub)/profile/components/KeywordPopup.tsx
  src/app/(sub)/profile/components/MultiValueResponsePopup.tsx
  src/app/(sub)/profile/components/MyKeyword.tsx
  src/app/(sub)/profile/components/ProfileContext.tsx
  src/app/(sub)/profile/components/ProfileForm.tsx
  src/app/(sub)/profile/components/ProfileHeader.tsx
  src/app/(sub)/profile/components/SelfIntro.tsx
  src/app/(sub)/profile/components/SingleValueResponseEditPopup.tsx
  src/app/(sub)/profile/components/ValueResponseList.tsx
  src/app/(sub)/profile/page.tsx
  src/app/(sub)/profile/type.ts
  src/app/(sub)/profile/utils/index.ts
  src/components/Header/Header.tsx
  src/components/Input.tsx
  src/components/Overlay/BottomSheet.tsx
  src/components/Overlay/PopupContainer.tsx
  src/components/Overlay/Portal.tsx
  src/components/ProfileCard.tsx
  src/components/TextField.tsx
  src/hooks/index.ts
  src/hooks/useDynamicTextareaHeight.ts
  src/middleware.ts
  src/providers/FileFormProvider.tsx
  src/types/index.d.ts
  src/utils/getEmptyProfile.ts
  src/utils/token.ts
Labels: 기능구현 ✅

#99 1차 QA 대비 리펙토링
  src/apis/question/queries.ts
  src/app/(sub)/join/funnels/step2/components/BodyTypeSection.tsx
  src/app/(sub)/join/funnels/step2/components/Keywords.tsx
  src/app/(sub)/join/funnels/step2/components/MyKeywordPopup.tsx
  src/app/(sub)/join/funnels/step4/components/QuestionList.tsx
  src/app/(sub)/join/funnels/step6/Step6.tsx
  src/app/(sub)/profile/components/MultiValueResponsePopup.tsx
  src/app/(sub)/profile/components/ProfileForm.tsx
  src/app/(sub)/profile/components/SingleValueResponseEditPopup.tsx
  src/components/ProfileCard.tsx
  src/hooks/useApiError.ts
  src/providers/FileFormProvider.tsx
  src/providers/Providers.tsx
  src/providers/QueryProvider.tsx
  src/providers/ToastProvider.tsx
Labels: 리펙토링 ♻️, 버그 🚨

#101 온보딩 페이지 영상으로 교체
  public/video/onboarding1.mp4
  public/video/onboarding2.mp4
  public/video/onboarding3.mp4
  src/app/page.tsx
  src/components/Video.tsx
Labels: 기능구현 ✅

#108 피드 조회 리스트 수정 및 피드 상세페이지 구현
  next.config.js
  public/svg/alarm.svg
  public/svg/bottomTabBar/chatting-off.svg
  public/svg/bottomTabBar/chatting-on.svg
  public/svg/bottomTabBar/feed-off.svg
  public/svg/bottomTabBar/feed-on.svg
  public/svg/bottomTabBar/home-off.svg
  public/svg/bottomTabBar/home-on.svg
  public/svg/bottomTabBar/like-off.svg
  public/svg/bottomTabBar/like-on.svg
  public/svg/bottomTabBar/my-off.svg
  public/svg/bottomTabBar/my-on.svg
  public/svg/create.svg
  public/svg/female.svg
  public/svg/like-off.svg
  public/svg/like-on.svg
  public/svg/male.svg
  src/apis/feed/apis.ts
  src/apis/feed/keys.ts
  src/apis/feed/queries.ts
  src/apis/feed/type.ts
  src/app/(main)/feed/components/ChannelBadge.tsx
  src/app/(main)/feed/components/FeedHeader.tsx
  src/app/(main)/feed/components/FeedItem.tsx
  src/app/(main)/feed/components/LikeCount.tsx
  src/app/(main)/feed/create/page.tsx
  src/app/(main)/feed/detail/[id]/page.tsx
  src/app/(main)/feed/page.tsx
  src/components/TabBar/BottomTabBar.tsx
  src/types/svgr.d.ts
Labels: 기능구현 ✅, 리펙토링 ♻️

#107 2차 QA
  package.json
  public/image/onboarding1.png
  public/image/onboarding2.png
  public/image/onboarding3.png
  public/lottie/loading-box.json
  public/svg/join-step1.svg
  public/svg/join-step2.svg
  public/video/chat-request.mp4
  public/video/step1-girl.mp4
  public/video/step3-boy.mp4
  src/apis/profile/type.ts
  src/apis/question/queries.ts
  src/app/(sub)/join/components/Join1Context.tsx
  src/app/(sub)/join/funnels/step1/Step1.tsx
  src/app/(sub)/join/funnels/step3/Step3.tsx
  src/app/(sub)/join/funnels/step4/components/QuestionList.tsx
  src/app/(sub)/profile/[id]/components/ChatRequestBottomSheet.tsx
  src/app/(sub)/profile/[id]/components/StarRating.tsx
  src/app/(sub)/profile/[id]/page.tsx
  src/app/(sub)/profile/approved/[id]/page.tsx
  src/app/(sub)/profile/approved/components/ApprovedSection.tsx
  src/app/(sub)/profile/components/KeywordPopup.tsx
  src/app/(sub)/profile/components/MultiValueResponsePopup.tsx
  src/app/(sub)/profile/components/MyKeyword.tsx
  src/app/(sub)/profile/components/ProfileContext.tsx
  src/app/(sub)/profile/components/ProfileForm.tsx
  src/app/(sub)/profile/components/SelfIntro.tsx
  src/app/(sub)/profile/components/SingleValueResponseEditPopup.tsx
  src/app/(sub)/profile/components/ValueResponseList.tsx
  src/app/(sub)/profile/page.tsx
  src/app/(sub)/profile/utils/index.ts
  src/components/Video.tsx
  src/types/index.d.ts
  yarn.lock
Labels: 리펙토링 ♻️
